version: '3.1'

networks:
  lared:
    driver: bridge

services:
  api:
    container_name: api
    build: ./api
    depends_on:
       - apache-kafka
    ports:
      - "3000:3000"
        
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    
  apache-kafka:
    container_name: apache-kafka
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"   
      KAFKA_ADVERTISED_PORT: "9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092
 
  # database:
  #   container_name: database
  #   image: bitnami/postgresql:14.5.0
  #   enviroment:
  #     - POSTGRESQL_USERNAME=postgres
  #     - POSTGRESQL_PASSWORD=postgres
  #     - POSTGRESQL_DATABASE=postgres
  #   ports:
  #     - 5432:5432
