version: '3.1'

services:
  api:
    container_name: api
    build: ./api
    restart: always
    depends_on:
       - kafka
       - zookeeper
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
        
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"   
      KAFKA_ADVERTISED_PORT: "9092"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_NUM_PARTITIONS: 2
    ports:
      - 9092:9092
      
  registro:
    build: ./registro
    restart: always
    environment:
      kafkaHost: kafka:9092
      PORT: 3000
    depends_on:
      - api
      - kafka
      - zookeeper
    ports:
     - 4000:3000
     
  agentextra:
    build: ./agentextra
    restart: always
    environment:
      kafkaHost: kafka:9092
      PORT: 3000
    depends_on:
      - api
      - kafka
      - zookeeper
    ports:
     - 4001:3000
    
  registroventa:
    build: ./registroventa
    restart: always
    environment:
      kafkaHost: kafka:9092
      PORT: 3000
    depends_on:
      - api
      - kafka
      - zookeeper
    ports:
     - 4002:3000
     
  stock:
    build: ./stock
    restart: always
    environment:
      kafkaHost: kafka:9092
      PORT: 3000
    depends_on:
      - api
      - kafka
      - zookeeper
    ports:
     - 4003:3000
     
  ubicacion:
    build: ./ubicacion
    restart: always
    environment:
      kafkaHost: kafka:9092
      PORT: 3000
    depends_on:
      - api
      - kafka
      - zookeeper
    ports:
     - 4004:3000
      
  # database:
  #   container_name: database
  #   image: bitnami/postgresql:14.5.0
  #   enviroment:
  #     - POSTGRESQL_USERNAME=postgres
  #     - POSTGRESQL_PASSWORD=postgres
  #     - POSTGRESQL_DATABASE=postgres
  #   ports:
  #     - 5432:5432

